export const PRODUCTS = [
  {
    id: 'protrackng',
    name: 'ProTrackNG',
    tagline: 'Tender Intelligence Platform',
    desc: 'Centralised tender tracking for Nigerian procurement teams. Monitors government portals, sets deadline alerts, manages bid documents, and gives management a real-time pipeline view — all in one platform built for the Nigerian market.',
    status: 'LIVE' as const,
    color: '#06B6D4',
    icon: '◎',
    domain: 'protrackng.com',
    metrics: ['Oil & Gas clients live', 'Real-time deadline alerts', 'Role-based bid pipeline'],
    stack: ['React', 'Node.js', 'PostgreSQL', 'Python'],
    category: 'B2B SaaS',
  },
  {
    id: 'nightops',
    name: 'NightOps',
    tagline: 'Nightlife Operating System',
    desc: 'Full operational platform for nightclubs and entertainment venues. Table management, bottle tracking, staff shift logging, real-time revenue dashboard, inventory control, and end-of-night reconciliation in one unified system.',
    status: 'LIVE' as const,
    color: '#A78BFA',
    icon: '◈',
    domain: 'nightops.prostackng.com',
    metrics: ['Full ops digitalisation', 'Real-time revenue dashboard', 'Nightly reconciliation in minutes'],
    stack: ['React', 'Node.js', 'PostgreSQL', 'Supabase'],
    category: 'SaaS / POS',
  },
  {
    id: 'autoreport',
    name: 'AutoReport',
    tagline: 'Automated Executive Reporting',
    desc: 'An automated reporting pipeline that loads raw sales data, calculates KPIs, builds charts, generates a branded PDF and multi-sheet Excel workbook, then emails everything on a daily schedule — no manual effort after setup.',
    status: 'LIVE' as const,
    color: '#FF5757',
    icon: '▦',
    domain: 'autoreport.prostackng.com',
    metrics: ['~8 seconds full pipeline', 'Branded PDF + Excel output', 'Scheduled daily delivery'],
    stack: ['Python', 'Pandas', 'ReportLab', 'OpenPyXL', 'SMTP'],
    category: 'Data Automation',
  },
  {
    id: 'myharriet',
    name: 'MyHarriet',
    tagline: 'Commerce & Marketplace Platform',
    desc: 'A marketplace platform built for Nigerian commerce — vendor profiles, escrow-backed payments, parcel tracking, and a campus-first launch strategy. Designed to connect buyers and sellers with trust at every layer.',
    status: 'BUILDING' as const,
    color: '#F5B530',
    icon: '⬡',
    domain: 'myharriet.com',
    metrics: ['Escrow payment system', 'Vendor profiles & ratings', 'Campus-first launch'],
    stack: ['Next.js', 'Node.js', 'PostgreSQL', 'Paystack'],
    category: 'Marketplace',
  },
  {
    id: 'swiftride',
    name: 'SwiftRide',
    tagline: 'Mobility & Ride-Hailing Platform',
    desc: 'Ride-hailing built for Rivers State and surrounding areas. Real-time GPS tracking, driver earnings dashboards, in-app SOS, and Mapbox navigation optimised for Nigerian road conditions.',
    status: 'ROADMAP' as const,
    color: '#38BDF8',
    icon: '⟁',
    domain: 'swiftride.com',
    metrics: ['Rivers & Bayelsa launch target', 'Live GPS tracking', 'Driver earnings dashboard'],
    stack: ['React Native', 'Node.js', 'WebSockets', 'Mapbox', 'Redis'],
    category: 'Mobility Tech',
  },
  {
    id: 'stakex',
    name: 'StakeX',
    tagline: 'Digital Staking Platform',
    desc: "A digital staking and prediction platform for Africa's growing digital economy. Built on auditable infrastructure with real-time settlement and responsible gaming controls built into the core architecture.",
    status: 'ROADMAP' as const,
    color: '#FB923C',
    icon: '◑',
    domain: 'stakex.com',
    metrics: ['Phase 4 launch', 'Auditable settlement', 'Responsible gaming controls'],
    stack: ['React', 'Node.js', 'PostgreSQL'],
    category: 'FinTech',
  },
];

export const CASE_STUDIES = [
  {
    product: 'AutoReport',
    color: '#FF5757',
    title: 'From 3-hour manual grind to automated daily delivery',
    client: 'Corporate Sales Organisation, Port Harcourt',
    problem: 'A corporate sales team manually compiled weekly Excel reports — a process consuming 2–3 hours per day, prone to formatting errors, inconsistent KPI calculations, and last-minute delays that frustrated management.',
    solution: 'We built a Python automation pipeline: loads raw CSV or Excel data, cleans and validates it, calculates all KPIs, generates charts, produces a branded PDF report and a multi-sheet Excel workbook, then emails both files with an HTML summary on a daily schedule.',
    result: "Zero manual effort after setup. Reports arrive in the MD's inbox every morning before they start work. Consistent formatting, every time.",
    metric: '~8 sec',
    metricLabel: 'Full pipeline runtime',
  },
  {
    product: 'NightOps',
    color: '#A78BFA',
    title: 'A Port Harcourt venue that knows its numbers in real time',
    client: 'Nightclub & Entertainment Venue, Port Harcourt',
    problem: 'A high-volume nightclub had no visibility into real-time revenue, reconciled cash manually at the end of every night, and could not track which tables, staff, or products were actually driving profitability.',
    solution: 'NightOps replaced every manual process — table reservations, bottle service tracking, shift management, stock alerts, and end-of-night reconciliation — with a unified real-time dashboard accessible from any device.',
    result: 'Full operations digitalised. Nightly reconciliation reduced from over two hours to under five minutes.',
    metric: '2hrs → 5min',
    metricLabel: 'Nightly reconciliation',
  },
  {
    product: 'ProTrackNG',
    color: '#06B6D4',
    title: 'Tender pipeline visibility for an oil & gas procurement team',
    client: 'Oil & Gas Procurement Team, Port Harcourt',
    problem: 'An oil and gas procurement team managed tenders across multiple government portals, email chains, and spreadsheets — missing deadlines and losing bids due to disorganisation and lack of a central system.',
    solution: 'ProTrackNG centralised their entire tender pipeline with role-based access, deadline alerting, bid document storage, and a management dashboard showing live bid status across all active opportunities.',
    result: 'Complete pipeline visibility from day one. No more missed deadlines. Bid preparation more organised and consistent.',
    metric: '100%',
    metricLabel: 'Pipeline visibility',
  },
];

export const STACK = [
  { label: 'Frontend',       color: '#06B6D4', items: ['Next.js', 'React', 'React Native', 'TypeScript', 'Tailwind CSS'] },
  { label: 'Backend',        color: '#38BDF8', items: ['Node.js', 'Python', 'FastAPI', 'REST APIs', 'WebSockets'] },
  { label: 'Database',       color: '#A78BFA', items: ['PostgreSQL', 'Supabase', 'Redis', 'SQLite'] },
  { label: 'Infrastructure', color: '#F5B530', items: ['Vercel', 'Cloudflare', 'Docker', 'GitHub Actions'] },
  { label: 'Payments',       color: '#FF5757', items: ['Paystack', 'Flutterwave', 'Remita', 'Escrow Wallets'] },
  { label: 'Data & AI',      color: '#FB923C', items: ['Pandas', 'ReportLab', 'OpenPyXL', 'OpenAI APIs', 'Umami Analytics'] },
];

export const SHARED_SERVICES = [
  { subdomain: 'auth.prostackng.com',      desc: 'Shared SSO — one account works across all ProStack NG products',            color: '#06B6D4' },
  { subdomain: 'api.prostackng.com',       desc: 'Central API gateway routing requests to each product backend',               color: '#38BDF8' },
  { subdomain: 'payments.prostackng.com',  desc: 'Unified Paystack and Flutterwave integration used across all products',      color: '#F5B530' },
  { subdomain: 'notify.prostackng.com',    desc: 'Email, WhatsApp, and push notifications shared across the platform',         color: '#A78BFA' },
  { subdomain: 'analytics.prostackng.com', desc: 'Umami self-hosted analytics — privacy-first, no cookie consent required',    color: '#FF5757' },
  { subdomain: 'cdn.prostackng.com',       desc: 'Cloudflare-powered static asset and media delivery for all products',        color: '#FB923C' },
];

export const TIMELINE = [
  { phase: 'Phase 1', period: '2024 – 2025', status: 'active',  desc: 'ProTrackNG, NightOps, and AutoReport launched and live. 20+ paying clients across Port Harcourt, Lagos, and Abuja. Revenue-generating. Fully bootstrapped.' },
  { phase: 'Phase 2', period: '2026',         status: 'next',    desc: 'MyHarriet beta — campus and neighbourhood marketplace launch in Port Harcourt. Escrow payments, vendor onboarding, and parcel tracking go live.' },
  { phase: 'Phase 3', period: '2026 – 2027',  status: 'planned', desc: 'SwiftRide — Rivers State and Bayelsa ride-hailing launch. Shared authentication and payment infrastructure fully operational across all products.' },
  { phase: 'Phase 4', period: '2027',          status: 'planned', desc: 'StakeX launch. Full platform ecosystem complete. Seed / pre-Series A raise targeting ₦75M–₦150M to scale engineering and sales.' },
];

export const COMPANY_STATS = [
  { value: 6,  suffix: '',  label: 'Platforms Built or In Progress' },
  { value: 20, suffix: '+', label: 'Paying Clients'                 },
  { value: 3,  suffix: '',  label: 'Live Platforms'                 },
  { value: 0,  suffix: '',  label: 'Outside Capital Raised'         },
];

export type Product   = typeof PRODUCTS[number];
export type CaseStudy = typeof CASE_STUDIES[number];
